import { Injectable, Logger } from '@nestjs/common';
import type { TDocumentDefinitions } from 'pdfmake/interfaces.js';

// pdfmake 0.3.x: the top-level `pdfmake` package exports a singleton
// (virtualfs + urlResolver), NOT the Printer class. The class lives at
// `pdfmake/js/Printer`. @types/pdfmake doesn't ship types for that subpath.
// Project compiles to CommonJS (per tsconfig), so require() is available.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PdfPrinter: any = require('pdfmake/js/Printer').default;

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private readonly printer: any;

  constructor() {
    this.printer = new PdfPrinter({
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique',
      },
    });
  }

  async generatePdf(
    report: any,
    employees: any[],
    riskSnapshots: any[],
  ): Promise<Buffer> {
    this.logger.log(`Generating PDF for report ${report.id}...`);

    const snapshotMap = new Map<string, any>();
    for (const snap of riskSnapshots) {
      snapshotMap.set(snap.employeeId, snap);
    }

    const docDefinition = this.buildDocument(report, employees, snapshotMap);
    return this.renderToBuffer(docDefinition);
  }

  private buildDocument(
    report: any,
    employees: any[],
    snapshotMap: Map<string, any>,
  ): TDocumentDefinitions {
    const riskColor = this.getRiskColor(report.riskScore);
    const riskLabel = this.getRiskLabel(report.riskScore);
    const generatedDate = new Date(report.createdAt).toLocaleDateString(
      'en-US',
      { year: 'numeric', month: 'long', day: 'numeric' },
    );
    const generatedBy = report.generatedByUser
      ? `${report.generatedByUser.firstName} ${report.generatedByUser.lastName}`
      : 'System';

    const actionPlan =
      report.actionPlans?.[0]?.planJson ||
      report.actionPlan?.planJson ||
      {};
    const priorities = actionPlan.priorities || [];
    const strategies = actionPlan.retentionStrategies || [];

    return {
      defaultStyle: { font: 'Helvetica', fontSize: 10 },

      header: {
        text: 'HR INSIGHT AI — Confidential',
        alignment: 'right',
        margin: [0, 15, 40, 0],
        fontSize: 8,
        color: '#999999',
      },

      footer: (currentPage: number, pageCount: number) => ({
        columns: [
          {
            text: 'Generated by HR Insight AI | Confidential — Internal Use Only',
            alignment: 'left',
            margin: [40, 0, 0, 0],
            fontSize: 8,
            color: '#999999',
          },
          {
            text: `Page ${currentPage} of ${pageCount}`,
            alignment: 'right',
            margin: [0, 0, 40, 0],
            fontSize: 8,
            color: '#999999',
          },
        ],
      }),

      content: [
        {
          text: 'Workforce Risk Assessment Report',
          fontSize: 22,
          bold: true,
          color: '#1a1a2e',
          margin: [0, 0, 0, 5],
        },
        {
          canvas: [
            {
              type: 'line',
              x1: 0,
              y1: 0,
              x2: 515,
              y2: 0,
              lineWidth: 2,
              lineColor: '#1890ff',
            },
          ],
          margin: [0, 0, 0, 15],
        },

        {
          columns: [
            {
              width: '50%',
              stack: [
                {
                  text: [
                    { text: 'Team: ', bold: true },
                    `${report.team?.name || 'Unknown'} (${report.team?.department || ''})`,
                  ],
                },
                {
                  text: [
                    { text: 'Report Period: ', bold: true },
                    `${new Date(report.dateRangeStart).toLocaleDateString('en-US')} — ${new Date(report.dateRangeEnd).toLocaleDateString('en-US')}`,
                  ],
                  margin: [0, 3, 0, 0],
                },
                {
                  text: [
                    { text: 'Generated: ', bold: true },
                    `${generatedDate} by ${generatedBy}`,
                  ],
                  margin: [0, 3, 0, 0],
                },
              ],
            },
            {
              width: '50%',
              alignment: 'right',
              stack: [
                { text: 'Overall Risk Score', bold: true, fontSize: 11 },
                {
                  text: `${report.riskScore ?? 0}%`,
                  fontSize: 32,
                  bold: true,
                  color: riskColor,
                },
                {
                  text: riskLabel,
                  fontSize: 12,
                  bold: true,
                  color: riskColor,
                },
              ],
            },
          ],
          margin: [0, 0, 0, 20],
        },

        {
          text: 'Executive Summary',
          fontSize: 16,
          bold: true,
          color: '#1a1a2e',
          margin: [0, 0, 0, 8],
        },
        {
          text: this.stripMarkdown(
            report.summaryText || 'No summary available.',
          ),
          fontSize: 10,
          lineHeight: 1.4,
          margin: [0, 0, 0, 20],
        },

        ...(priorities.length > 0
          ? [
              {
                text: 'Action Plan — Priorities',
                fontSize: 16,
                bold: true,
                color: '#1a1a2e',
                margin: [0, 0, 0, 8] as [number, number, number, number],
              },
              {
                table: {
                  headerRows: 1,
                  widths: ['auto', '*', 'auto', 'auto', 'auto'],
                  body: [
                    [
                      {
                        text: '#',
                        bold: true,
                        fillColor: '#1890ff',
                        color: '#ffffff',
                      },
                      {
                        text: 'Priority',
                        bold: true,
                        fillColor: '#1890ff',
                        color: '#ffffff',
                      },
                      {
                        text: 'Impact',
                        bold: true,
                        fillColor: '#1890ff',
                        color: '#ffffff',
                      },
                      {
                        text: 'Timeline',
                        bold: true,
                        fillColor: '#1890ff',
                        color: '#ffffff',
                      },
                      {
                        text: 'Cost',
                        bold: true,
                        fillColor: '#1890ff',
                        color: '#ffffff',
                      },
                    ],
                    ...priorities.map((p: any, i: number) => [
                      { text: String(i + 1), alignment: 'center' },
                      {
                        stack: [
                          { text: p.title, bold: true },
                          {
                            text: p.description || '',
                            fontSize: 8,
                            color: '#666666',
                          },
                        ],
                      },
                      {
                        text: p.impact || 'N/A',
                        color:
                          p.impact === 'HIGH'
                            ? '#ff4d4f'
                            : p.impact === 'MEDIUM'
                              ? '#faad14'
                              : '#52c41a',
                        bold: true,
                      },
                      { text: p.timeline || 'N/A' },
                      { text: p.estimatedCost || 'N/A' },
                    ]),
                  ],
                },
                layout: 'lightHorizontalLines',
                margin: [0, 0, 0, 20] as [number, number, number, number],
              },
            ]
          : []),

        ...(strategies.length > 0
          ? [
              {
                text: 'Retention Strategies',
                fontSize: 14,
                bold: true,
                color: '#1a1a2e',
                margin: [0, 0, 0, 8] as [number, number, number, number],
              },
              ...strategies.map((s: any) => ({
                stack: [
                  {
                    text: `${s.strategy} — targeting: ${s.targetGroup || 'N/A'}`,
                    bold: true,
                    margin: [0, 0, 0, 3] as [number, number, number, number],
                  },
                  {
                    text: `Expected impact: ${s.expectedImpact || 'N/A'}`,
                    fontSize: 9,
                    color: '#666666',
                    margin: [0, 0, 0, 3] as [number, number, number, number],
                  },
                  {
                    ul: (s.steps || []).map((step: string) => ({
                      text: step,
                      fontSize: 9,
                    })),
                    margin: [15, 0, 0, 10] as [number, number, number, number],
                  },
                ],
              })),
              {
                text: '',
                margin: [0, 0, 0, 10] as [number, number, number, number],
              },
            ]
          : []),

        {
          text: 'Employee Risk Details',
          fontSize: 16,
          bold: true,
          color: '#1a1a2e',
          margin: [0, 10, 0, 8],
          pageBreak: 'before' as const,
        },
        {
          table: {
            headerRows: 1,
            widths: ['*', 'auto', 'auto', 'auto', 'auto'],
            body: [
              [
                {
                  text: 'Employee',
                  bold: true,
                  fillColor: '#1890ff',
                  color: '#ffffff',
                },
                {
                  text: 'Risk Score',
                  bold: true,
                  fillColor: '#1890ff',
                  color: '#ffffff',
                },
                {
                  text: 'Risk Level',
                  bold: true,
                  fillColor: '#1890ff',
                  color: '#ffffff',
                },
                {
                  text: 'Engagement',
                  bold: true,
                  fillColor: '#1890ff',
                  color: '#ffffff',
                },
                {
                  text: 'Tenure (mo)',
                  bold: true,
                  fillColor: '#1890ff',
                  color: '#ffffff',
                },
              ],
              ...employees
                .map((emp) => {
                  const snap = snapshotMap.get(emp.id);
                  const score = snap?.riskScore ?? 0;
                  const level = snap?.riskLevel ?? 'N/A';
                  return { emp, score, level };
                })
                .sort((a, b) => b.score - a.score)
                .map(({ emp, score, level }) => [
                  { text: emp.name },
                  {
                    text: `${score}%`,
                    color: this.getRiskColor(score),
                    bold: true,
                    alignment: 'center',
                  },
                  {
                    text: String(level),
                    color: this.getRiskColor(score),
                    bold: true,
                  },
                  {
                    text: emp.engagementScore?.toFixed(1) || 'N/A',
                    alignment: 'center',
                  },
                  {
                    text: String(emp.tenureMonths ?? 'N/A'),
                    alignment: 'center',
                  },
                ]),
            ],
          },
          layout: 'lightHorizontalLines',
        },
      ],

      pageSize: 'A4',
      pageMargins: [40, 50, 40, 50],
    };
  }

  private async renderToBuffer(
    docDefinition: TDocumentDefinitions,
  ): Promise<Buffer> {
    // pdfmake 0.3.x: createPdfKitDocument is async. It resolves to a
    // PDFKit-style stream; we collect chunks to a Buffer.
    const doc: any = await this.printer.createPdfKitDocument(docDefinition);

    return new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err: Error) => reject(err));
      doc.end();
    });
  }

  private getRiskColor(score: number | null | undefined): string {
    const s = score ?? 0;
    if (s >= 70) return '#ff4d4f';
    if (s >= 40) return '#faad14';
    return '#52c41a';
  }

  private getRiskLabel(score: number | null | undefined): string {
    const s = score ?? 0;
    if (s >= 70) return 'HIGH RISK';
    if (s >= 40) return 'MEDIUM RISK';
    return 'LOW RISK';
  }

  private stripMarkdown(text: string): string {
    return text
      .replace(/#{1,6}\s*/g, '')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/^[-*]\s/gm, '• ')
      .trim();
  }
}
